### PR TITLE
doc(release): server-3.9.1

### PR DESCRIPTION
**Pull request by definite**
Blogging for server-3.9.1 release.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata.github.io/33)

### CODE REVIEW

**Comment by kathryngo** [comment]
*[_posts/2016-07-15-zanata-version-3-9-1.md, line 18 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KMvhcIJPrhl9i0yqSOQ:-KMvhcIJPrhl9i0yqSOR:-940627141) ([raw file](https://github.com/zanata/zanata.github.io/blob/3d58236b7a4ac9c72fd8cbef8eeb575e7c5cf113/_posts/2016-07-15-zanata-version-3-9-1.md#L18)):*
> ```Markdown
> ## Highlights
> 
> This release does not have much UI changes that are observable to the end-users that use only our web interface. However, this version has many improvement for REST API users and system administrators.
> ```

should be
*many UI changes
*this version has many improvements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/33)*

**Comment by kathryngo** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2016-07-15-zanata-version-3-9-1.md, line 18 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KMvhcIJPrhl9i0yqSOQ:-KNACqJqI3TbJ6Zfz5Og:-68394029) ([raw file](https://github.com/zanata/zanata.github.io/blob/3d58236b7a4ac9c72fd8cbef8eeb575e7c5cf113/_posts/2016-07-15-zanata-version-3-9-1.md#L18)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary>
> should be
> *many UI changes
> *this version has many improvements
</details>
Should be 
This release includes many UI changes and improvements to the web interface for web UI users, REST API users and system administrators.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/33)*

**Comment by davidmason** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[_posts/2016-08-10-zanata-version-3-9-3.md, line 13 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KOr5nPm20_n6GJKBoYF:-KOr5nPm20_n6GJKBoYG:b-yhs7t9) ([raw file](https://github.com/zanata/zanata.github.io/blob/984e4a2e4a489f10af42951f467de4f3b467ebfa/_posts/2016-08-10-zanata-version-3-9-3.md#L13)):*
> ```Markdown
> author_username: definite
> ---
> zanata-server-3.9.3 is released and deploy to all our servers.
> ```

`... and deployed to ...`

---

*[_posts/2016-08-10-zanata-version-3-9-3.md, line 18 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KOr9urwnRS6JW03EPMR:-KOr9urwnRS6JW03EPMS:b-f3xbfx) ([raw file](https://github.com/zanata/zanata.github.io/blob/984e4a2e4a489f10af42951f467de4f3b467ebfa/_posts/2016-08-10-zanata-version-3-9-3.md#L18)):*
> ```Markdown
> 
> This release fixes the login problems for Fedora and Yahoo
> authentication. As will as many UI changes and improvements to the web interface for web UI users, REST API users and system administrators.
> ```

Should only use "as well as" when continuing a sentence, not at the start of a sentence.

---

*[_posts/2016-08-10-zanata-version-3-9-3.md, line 20 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KOr6HCGl6SOGG6XRlaK:-KOr6HCGl6SOGG6XRlaL:b9z01mr) ([raw file](https://github.com/zanata/zanata.github.io/blob/984e4a2e4a489f10af42951f467de4f3b467ebfa/_posts/2016-08-10-zanata-version-3-9-3.md#L20)):*
> ```Markdown
> authentication. As will as many UI changes and improvements to the web interface for web UI users, REST API users and system administrators.
> 
> ### For Web UI End Users
> ```

Does this mean people who use the editor? We could make that more clear if so.

---

*[_posts/2016-08-10-zanata-version-3-9-3.md, line 37 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KOr6VUFrh1efihk4Tac:-KOr6VUFrh1efihk4Tad:bpo2cr3) ([raw file](https://github.com/zanata/zanata.github.io/blob/984e4a2e4a489f10af42951f467de4f3b467ebfa/_posts/2016-08-10-zanata-version-3-9-3.md#L37)):*
> ```Markdown
> 
> - [Release Note for 3.9.1](http://docs.zanata.org/en/latest/release-notes/#391)
> - [Release Note for 3.9.0](http://docs.zanata.org/en/latest/release-notes/#390)
> ```

Change these to say `Release Notes for ...`

---

*[_posts/2016-08-10-zanata-version-3-9-3.md, line 38 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-KOr9NRfQljLYUQMZvkv:-KOr9NRgQngErPRZbzoa:bfhbhwm) ([raw file](https://github.com/zanata/zanata.github.io/blob/984e4a2e4a489f10af42951f467de4f3b467ebfa/_posts/2016-08-10-zanata-version-3-9-3.md#L38)):*
> ```Markdown
> - [Release Note for 3.9.1](http://docs.zanata.org/en/latest/release-notes/#391)
> - [Release Note for 3.9.0](http://docs.zanata.org/en/latest/release-notes/#390)
> - [Download zanata-server-3.9.1](https://github.com/zanata/zanata-server/releases/tag/server-3.9.1)
> ```

This link does not actually start a download. Maybe the text should indicate that it will show the downloads page?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/33)*

**Comment by kathryngo** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/33)*

**Comment by kathryngo** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/33#-:-KOrgdAsufWmLXuVqjez:bnfp4nl)*

**Pull request merged**
