### PR TITLE
Update broken link

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1204982#c12
https://bugzilla.redhat.com/show_bug.cgi?id=1204982#c13

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:+1:

**Comment by aeng** [comment]
Merged into master. https://github.com/zanata/zanata.github.io/commit/4674e38a4a3f64c72296da625dad0dda136d3c8d

**Comment by seanf** [comment]
@aeng Did the Jenkins job show these broken links?

**Comment by aeng** [comment]
@seanf no.

**Comment by seanf** [comment]
@aeng any idea why?  Should we be using different options to LinkChecker?

**Comment by aeng** [comment]
@seanf Think the linkChecker is configure to check intern URL only. Need to use --check-extern for external URL. I will look into that.

**Pull request closed without merging**
