### PR TITLE
doc(release): v3.9.5

### PR DESCRIPTION
**Pull request by definite**
Blog for version 3.9.5

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata.github.io/34)

### CODE REVIEW

**Comment by davidmason** [comment]
@definite is this assigned to me for review?

**Comment by davidmason** [comment]
Just those two little changes.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[_posts/2016-09-02-zanata-version-3-9-5.md, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/34#-KQd_ngUI3jwKU8XQjBd:-KQd_ngVkwvuesGq27_5:b-jz2k8) ([raw file](https://github.com/zanata/zanata.github.io/blob/864f5dac2e7b29f32deecbbee60cf8a3ca49d0a5/_posts/2016-09-02-zanata-version-3-9-5.md#L14)):*
> ```Markdown
> ---
> zanata-server-3.9.5 is released and deployed to all our servers.
> The improvement since last deploy (version 3.9.3) are:
> ```

`... improvements ...`

---

*[_posts/2016-09-02-zanata-version-3-9-5.md, line 17 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata.github.io/34#-KQd_wMW5nkLFxMJfgm1:-KQd_wMXxOvTxEw6Qq-r:b-fezf2n) ([raw file](https://github.com/zanata/zanata.github.io/blob/864f5dac2e7b29f32deecbbee60cf8a3ca49d0a5/_posts/2016-09-02-zanata-version-3-9-5.md#L17)):*
> ```Markdown
> 
>  * Fixes the bug when users have non-ASCII characters in their full name,
>  * Javascript alert and confirm dialogs becomes modal
> ```

`... become modal ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/34#-:-KQda7PePTPNPJ2KopV1:b-nfdmkh)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/34#-:-KQekkzmuFy6pDi3toqE:bnfp4nl)*

**Comment by definite** [comment]
-(Awaiting review) +(Passed review) 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata.github.io/34#-:-KQsj4BmZfBepzA-GHoI:br4edgf)*

**Pull request merged**
